---
- name: Playbook that runs a ksh script
  hosts: localhost

  tasks:
  - name: Copy script to target hosts and execute it
    script: ~/mycode/scripts/kshscript.ksh
    args:
      executable: /usr/bin/ksh
    register: results    # save the JSON sent back by our script

  - name: Print out the 'results'
    debug:
      var: results
      # notice there is a stdout and stdout_lines
